name: Update Contributors

on:
  push:
    branches:
      - main

jobs:
  contrib-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p build

      - name: Generate contributors (avatars only)
        id: contributors
        uses: jaywcjlove/github-action-contributors@main
        with:
          output: build/CONTRIBUTORS.svg
          avatarSize: "36"

      - name: Update README with contributors
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: README.md
          body: |
            <style>.contributors img{border-radius:50%;}</style>
            <p align="center" class="contributors">${{ steps.contributors.outputs.htmlList }}</p>
          openDelimiter: "<!-- readme: contributors -start -->"
          closeDelimiter: "<!-- readme: contributors -end -->"
          message: "docs(contributor): update contributors in README"
